### ISSUE TITLE
Wont Run

### ISSUE THREAD

**Issue by jayjaytyper** [smar000/jlr2mqtt#1]
Hello, Managed to install this but when i run it i get the error below. any ideas?

>>> import jlr2mqtt.py
2020-03-22 17:46:55,276 - INFO - Connecting to mqtt server 192.168.1.5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/Desktop/jlr/jlr2mqtt.py", line 516, in <module>
    mqtt_client = initialise_mqtt_client(mqtt.Client(client_id=MQTT_CLIENTID))
  File "/home/pi/Desktop/jlr/jlr2mqtt.py", line 102, in initialise_mqtt_client
    mqtt_client.connect(MQTT_SERVER, port=1883, keepalive=0, bind_address="")
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
BlockingIOError: [Errno 115] Operation now in progress

**Comment by smar000** [comment]
Hi

Sorry, just saw your post. That looks like you haven't configured your mqtt broker details in the `.cfg` file.

**Comment by smar000** [comment]
Closing this issue as similar issue reported in [https://github.com/smar000/jlr2mqtt/issues/2].
